name: Deploy Pages
on:
  push:
    branches:
      - main
jobs:
  deploy_preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    timeout-minutes: 10
    environment:
      name: preview
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Deploy to Cloudflare Pages
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" -X GET "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pages/projects/favicon-preview" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}")
          if [ $response -eq 404 ]; then
            echo "Project does not exist, creating..."
            npx wrangler pages project create favicon-preview --production-branch main
          else
            echo "Project exists, skipping creation."
          fi
          sed -i 's/favicon/favicon-preview/' wrangler.toml
          npm run deploy 
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
